---
deployment:
  tasks:
    - echo "Pulling latest changes..."
    - /bin/git pull origin main
    - echo "Installing dependencies..."
    - /usr/local/bin/npm install
    - echo "Building Next.js app..."
    - /usr/local/bin/npm run build
    - echo "Deployment complete. Restart Node.js app manually if needed."
