---
deployment:
  tasks:
    # 1ï¸âƒ£ Set environment variables
    - export NEXT_PUBLIC_API_URL="https://brushedbybetty.com"
    - export DATABASE_URL="postgresql://neondb_owner:npg_T8cWokJtbzF3@ep-flat-heart-a4313ukx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
    - export RESEND_API_KEY="re_Q4CZLaoG_MpVCrd5XgUmiw3wMCVfBGgHP"
    - export JWT_SECRET="e317b068b89b0516730556868ce0b02cf684f21d0db0e510736e6954b1d1fff3"
    - export NEXTAUTH_URL="https://brushedbybetty.com"
    - export CHAPA_SECRET_KEY="CHASECK_TEST-BfX7iumQqjrxIy66sYTTpXm7TRYvVhny"
    - export NEXT_PUBLIC_UPLOAD_URL="https://brushedbybetty/uploads"
    - export CERTIFICATE_STORAGE_PATH="./public/certificates"
    - export CERTIFICATE_BASE_URL="https://brushedbybetty/certificates"

    # 2ï¸âƒ£ Set deployment path (your live site folder)
    - export DEPLOYPATH=/home/brushefj/public_html/

    # 3ï¸âƒ£ Start logging
    - echo "------ Starting Deployment ------" >> deploy-output.txt
    - echo "Current path: $PWD" >> deploy-output.txt

    # 4ï¸âƒ£ Move to repo root
    - cd $PWD

    # 5ï¸âƒ£ Install dependencies
    - echo "Running npm install..." >> deploy-output.txt
    - /usr/local/bin/npm install >> deploy-output.txt 2>&1

    # 6ï¸âƒ£ Build the Next.js site
    - echo "Running npm run build..." >> deploy-output.txt
    - /usr/local/bin/npm run build >> deploy-output.txt 2>&1

    # 7ï¸âƒ£ Export static files
    - echo "Running npm run export..." >> deploy-output.txt
    - /usr/local/bin/npm run export >> deploy-output.txt 2>&1

    # 8ï¸âƒ£ Clean old files from public_html
    - echo "Cleaning public_html..." >> deploy-output.txt
    - /bin/rm -rf $DEPLOYPATH/* >> deploy-output.txt 2>&1

    # 9ï¸âƒ£ Copy new files to public_html
    - echo "Copying files to public_html..." >> deploy-output.txt
    - /bin/cp -r out/* $DEPLOYPATH >> deploy-output.txt 2>&1

    # ðŸ”Ÿ Finish logging
    - echo "------ Deployment Finished ------" >> deploy-output.txt
