---
deployment:
  tasks:
    - export DEPLOYPATH=/home/brushefj/repositories/BBMI-LAST # Your application root
    - cd $DEPLOYPATH
    - echo "Pulling latest changes..."
    - /usr/bin/git pull origin main # Use /usr/bin/git for the Git binary
    - echo "Installing dependencies..."
    - /opt/cpanel/ea-nodejs22/bin/npm install --production # Replace XX with your Node.js version (e.g., 18, 20)
    - echo "Building Next.js app..."
    - /opt/cpanel/ea-nodejs22/bin/npm run build # Replace XX with your Node.js version
    - echo "Restarting Node.js application..."
    - /usr/bin/touch tmp/restart.txt
    - echo "Deployment complete."
