---
deployment:
  tasks:
    - export DEPLOYPATH=/home/brushefgj/public_html/
    - echo "------ Starting Deployment ------" >> deploy-output.txt
    - cd $PWD
    - echo "Running npm install..." >> deploy-output.txt
    - /usr/local/bin/npm install >> deploy-output.txt 2>&1
    - echo "Running npm run build..." >> deploy-output.txt
    - /usr/local/bin/npm run build >> deploy-output.txt 2>&1
    - echo "Running npm run export..." >> deploy-output.txt
    - /usr/local/bin/npm run export >> deploy-output.txt 2>&1
    - echo "Copying files to public_html..." >> deploy-output.txt
    - /bin/rm -rf $DEPLOYPATH/* >> deploy-output.txt 2>&1
    - /bin/cp -r out/* $DEPLOYPATH >> deploy-output.txt 2>&1
    - echo "------ Deployment Finished ------" >> deploy-output.txt
